export const codingQuestions = [
  // Blind 75 (Days 1-75)
  // Format: { title: "Two Sum", link: "https://leetcode.com/problems/two-sum/", difficulty: "Easy", phase: 1, type: "Coding" }
  { title: "Two Sum", link: "https://leetcode.com/problems/two-sum/", difficulty: "Easy", aha: "Use a hash map to store complements.", phase: 1, type: "Coding" },
  { title: "Best Time to Buy and Sell Stock", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "Easy", aha: "Track min_price and max_profit in one pass.", phase: 1, type: "Coding" },
  { title: "Contains Duplicate", link: "https://leetcode.com/problems/contains-duplicate/", difficulty: "Easy", aha: "Use a Set to check for existence in O(1).", phase: 1, type: "Coding" },
  { title: "Product of Array Except Self", link: "https://leetcode.com/problems/product-of-array-except-self/", difficulty: "Medium", aha: "Use prefix and suffix product arrays (or one array and a variable).", phase: 1, type: "Coding" },
  { title: "Maximum Subarray", link: "https://leetcode.com/problems/maximum-subarray/", difficulty: "Easy", aha: "Kadane's Algorithm: max_current vs max_global.", phase: 1, type: "Coding" },
  { title: "Maximum Product Subarray", link: "https://leetcode.com/problems/maximum-product-subarray/", difficulty: "Medium", aha: "Track min and max product because negatives flip signs.", phase: 1, type: "Coding" },
  { title: "Find Minimum in Rotated Sorted Array", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty: "Medium", aha: "Binary search: if mid > right, min is in right half.", phase: 1, type: "Coding" },
  { title: "Search in Rotated Sorted Array", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "Medium", aha: "Determine which half is sorted, then check if target is in range.", phase: 1, type: "Coding" },
  { title: "3Sum", link: "https://leetcode.com/problems/3sum/", difficulty: "Medium", aha: "Sort, fix one, use two pointers for the rest.", phase: 1, type: "Coding" },
  { title: "Container With Most Water", link: "https://leetcode.com/problems/container-with-most-water/", difficulty: "Medium", aha: "Two pointers from ends; move the shorter line inward.", phase: 1, type: "Coding" },
  // ... (Add more Blind 75 here)
  // For demo purposes, filling with placeholders to reach a reasonable number, but in real implementation would fill all 75.
  // Let's add few more iconic ones.
  { title: "Climbing Stairs", link: "https://leetcode.com/problems/climbing-stairs/", difficulty: "Easy", aha: "Fibonacci sequence: dp[i] = dp[i-1] + dp[i-2].", phase: 1, type: "Coding" },
  { title: "Coin Change", link: "https://leetcode.com/problems/coin-change/", difficulty: "Medium", aha: "Bottom-up DP: dp[amount] = min(dp[amount], dp[amount - coin] + 1).", phase: 1, type: "Coding" },
  { title: "Longest Increasing Subsequence", link: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "Medium", aha: "DP O(n^2) or Binary Search O(n log n).", phase: 1, type: "Coding" },
  { title: "Longest Common Subsequence", link: "https://leetcode.com/problems/longest-common-subsequence/", difficulty: "Medium", aha: "2D DP grid: if match, diag + 1; else max(up, left).", phase: 1, type: "Coding" },
  { title: "Word Break", link: "https://leetcode.com/problems/word-break/", difficulty: "Medium", aha: "dp[i] is true if dp[j] is true and s[j:i] in dict.", phase: 1, type: "Coding" },
  { title: "Combination Sum", link: "https://leetcode.com/problems/combination-sum/", difficulty: "Medium", aha: "Backtracking: include coin or skip coin.", phase: 1, type: "Coding" },
  { title: "House Robber", link: "https://leetcode.com/problems/house-robber/", difficulty: "Medium", aha: "dp[i] = max(dp[i-2] + nums[i], dp[i-1]).", phase: 1, type: "Coding" },
  { title: "House Robber II", link: "https://leetcode.com/problems/house-robber-ii/", difficulty: "Medium", aha: "Run House Robber twice: 0 to n-1 and 1 to n.", phase: 1, type: "Coding" },
  { title: "Decode Ways", link: "https://leetcode.com/problems/decode-ways/", difficulty: "Medium", aha: "Similar to climbing stairs but with conditions for '0'.", phase: 1, type: "Coding" },
  { title: "Unique Paths", link: "https://leetcode.com/problems/unique-paths/", difficulty: "Medium", aha: "dp[i][j] = dp[i-1][j] + dp[i][j-1].", phase: 1, type: "Coding" },
  { title: "Jump Game", link: "https://leetcode.com/problems/jump-game/", difficulty: "Medium", aha: "Greedy: keep track of max reachable index.", phase: 1, type: "Coding" },
  { title: "Clone Graph", link: "https://leetcode.com/problems/clone-graph/", difficulty: "Medium", aha: "DFS/BFS with a map to track visited nodes.", phase: 1, type: "Coding" },
  { title: "Course Schedule", link: "https://leetcode.com/problems/course-schedule/", difficulty: "Medium", aha: "Topological Sort (Kahn's or DFS cycle check).", phase: 1, type: "Coding" },
  { title: "Pacific Atlantic Water Flow", link: "https://leetcode.com/problems/pacific-atlantic-water-flow/", difficulty: "Medium", aha: "BFS/DFS from ocean edges inward.", phase: 1, type: "Coding" },
  { title: "Number of Islands", link: "https://leetcode.com/problems/number-of-islands/", difficulty: "Medium", aha: "DFS/BFS to mark '1's as '0's.", phase: 1, type: "Coding" },
  { title: "Longest Consecutive Sequence", link: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "Medium", aha: "Use a Set. Only start counting if num-1 is not in set.", phase: 1, type: "Coding" },
  { title: "Alien Dictionary", link: "https://leetcode.com/problems/alien-dictionary/", difficulty: "Hard", aha: "Topological Sort on character dependencies.", phase: 1, type: "Coding" },
  { title: "Graph Valid Tree", link: "https://leetcode.com/problems/graph-valid-tree/", difficulty: "Medium", aha: "Union-Find or DFS. Must have n-1 edges and no cycles.", phase: 1, type: "Coding" },
  { title: "Number of Connected Components", link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", difficulty: "Medium", aha: "Union-Find or DFS count.", phase: 1, type: "Coding" },
  { title: "Insert Interval", link: "https://leetcode.com/problems/insert-interval/", difficulty: "Medium", aha: "Add before, merge overlap, add after.", phase: 1, type: "Coding" },
  { title: "Merge Intervals", link: "https://leetcode.com/problems/merge-intervals/", difficulty: "Medium", aha: "Sort by start time, then merge.", phase: 1, type: "Coding" },
  { title: "Non-overlapping Intervals", link: "https://leetcode.com/problems/non-overlapping-intervals/", difficulty: "Medium", aha: "Greedy: sort by end time, pick non-conflicting.", phase: 1, type: "Coding" },
  { title: "Meeting Rooms", link: "https://leetcode.com/problems/meeting-rooms/", difficulty: "Easy", aha: "Sort by start time, check overlap.", phase: 1, type: "Coding" },
  { title: "Meeting Rooms II", link: "https://leetcode.com/problems/meeting-rooms-ii/", difficulty: "Medium", aha: "Min-Heap or Chronological Ordering (Start vs End).", phase: 1, type: "Coding" },
  { title: "Rotate Image", link: "https://leetcode.com/problems/rotate-image/", difficulty: "Medium", aha: "Transpose then reverse rows.", phase: 1, type: "Coding" },
  { title: "Spiral Matrix", link: "https://leetcode.com/problems/spiral-matrix/", difficulty: "Medium", aha: "Simulation with boundaries.", phase: 1, type: "Coding" },
  { title: "Set Matrix Zeroes", link: "https://leetcode.com/problems/set-matrix-zeroes/", difficulty: "Medium", aha: "Use first row/col as flags.", phase: 1, type: "Coding" },
  { title: "Search a 2D Matrix", link: "https://leetcode.com/problems/search-a-2d-matrix/", difficulty: "Medium", aha: "Treat as sorted list or double binary search.", phase: 1, type: "Coding" },
  { title: "Same Tree", link: "https://leetcode.com/problems/same-tree/", difficulty: "Easy", aha: "Recursion: root match && left match && right match.", phase: 1, type: "Coding" },
  { title: "Invert Binary Tree", link: "https://leetcode.com/problems/invert-binary-tree/", difficulty: "Easy", aha: "Swap left/right children recursively.", phase: 1, type: "Coding" },
  { title: "Maximum Depth of Binary Tree", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "Easy", aha: "1 + max(left, right).", phase: 1, type: "Coding" },
  { title: "Binary Tree Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "Medium", aha: "BFS with queue tracking level size.", phase: 1, type: "Coding" },
  { title: "Subtree of Another Tree", link: "https://leetcode.com/problems/subtree-of-another-tree/", difficulty: "Easy", aha: "Check identical for each node or serialize.", phase: 1, type: "Coding" },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", difficulty: "Medium", aha: "Preorder root is first; Inorder splits left/right.", phase: 1, type: "Coding" },
  { title: "Valid Binary Search Tree", link: "https://leetcode.com/problems/validate-binary-search-tree/", difficulty: "Medium", aha: "Maintain (min, max) range recursively.", phase: 1, type: "Coding" },
  { title: "Kth Smallest Element in a BST", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", difficulty: "Medium", aha: "Inorder traversal gives sorted elements.", phase: 1, type: "Coding" },
  { title: "Lowest Common Ancestor of a BST", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty: "Easy", aha: "If both < root, go left; if both > root, go right.", phase: 1, type: "Coding" },
  { title: "Implement Trie (Prefix Tree)", link: "https://leetcode.com/problems/implement-trie-prefix-tree/", difficulty: "Medium", aha: "Tree of nodes needing children[26].", phase: 1, type: "Coding" },
  { title: "Design Add and Search Words Data Structure", link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/", difficulty: "Medium", aha: "Trie + DFS for '.' wildcards.", phase: 1, type: "Coding" },
  { title: "Word Search II", link: "https://leetcode.com/problems/word-search-ii/", difficulty: "Hard", aha: "Trie + Backtracking on grid.", phase: 1, type: "Coding" },
  { title: "Merge k Sorted Lists", link: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "Hard", aha: "Min-heap of list heads.", phase: 1, type: "Coding" },
  { title: "Top K Frequent Elements", link: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "Medium", aha: "Min-heap of size K or Bucket Sort.", phase: 1, type: "Coding" },
  { title: "Find Median from Data Stream", link: "https://leetcode.com/problems/find-median-from-data-stream/", difficulty: "Hard", aha: "Two heaps: Max-heap (left) and Min-heap (right).", phase: 1, type: "Coding" },
];

export const systemDesignTopics = [
  // Phase 1: Core Concepts
  { title: "Scalability Basics", aha: "Vertical vs Horizontal Scaling, Single Point of Failure.", type: "System Design", phase: 1 },
  { title: "CAP Theorem", aha: "Consistency, Availability, Partition Tolerance. Pick 2.", type: "System Design", phase: 1 },
  { title: "ACID Transactions", aha: "Atomicity, Consistency, Isolation, Durability.", type: "System Design", phase: 1 },
  { title: "Consistent Hashing", aha: "Distributing data across nodes to minimize reorganization.", type: "System Design", phase: 1 },
  { title: "Load Balancing", aha: "L4 vs L7 balancing, Round Robin, Least Conn.", type: "System Design", phase: 1 },
  { title: "Caching Strategies", aha: "Write-through, Write-back, Write-around. Eviction policies (LRU).", type: "System Design", phase: 1 },
  { title: "Database Sharding", aha: "Partitioning data: Key-based, Range-based, Directory-based.", type: "System Design", phase: 1 },
  { title: "Replication Models", aha: "Master-Slave, Master-Master. Handling lag.", type: "System Design", phase: 1 },
  { title: "Proxies", aha: "Forward Proxy (Client side) vs Reverse Proxy (Server side).", type: "System Design", phase: 1 },
  { title: "CDN", aha: "Push vs Pull CDNs. Edge locations.", type: "System Design", phase: 1 },
  { title: "Message Queues", aha: "Decoupling services. Kafka vs RabbitMQ.", type: "System Design", phase: 1 },
  
  // Phase 2: Classic Problems (SDE 2)
  { title: "Design a URL Shortener", aha: "Base62 encoding, Collision handling, Pre-generation.", type: "System Design", phase: 2 },
  { title: "Design a Rate Limiter", aha: "Token Bucket, Leaky Bucket, Sliding Window.", type: "System Design", phase: 2 },
  { title: "Design a Key-Value Store", aha: "Dynamo style: Consistent hashing, Vector clocks, Gossip protocol.", type: "System Design", phase: 2 },
  { title: "Design a Unique ID Generator", aha: "Snowflake ID, UUID vs Int 64.", type: "System Design", phase: 2 },
  { title: "Design Pastebin", aha: "Metadata DB + Object Store (S3).", type: "System Design", phase: 2 },
  { title: "Design Twitter / News Feed", aha: "Fan-out on write vs Fan-out on read. Hybrid approach.", type: "System Design", phase: 2 },
  { title: "Design a Chat System", aha: "WebSockets, Long Polling, Preserving message order.", type: "System Design", phase: 2 },
  { title: "Design Web Crawler", aha: "BFS, Politeness, URL dedup (Bloom Filter).", type: "System Design", phase: 2 },
  
  // Phase 3: Specialized & Advanced
  { title: "IAM Architecture (SailPoint/Entra)", aha: "RBAC, ABAC, OAuth2 flows, JWT structure.", type: "System Design", phase: 3 },
  { title: "OAuth 2.0 & OIDC", aha: "Auth Code flow, PKCE, ID Token vs Access Token.", type: "System Design", phase: 3 },
  { title: "RAG Architecture", aha: "Vector DBs, Embeddings, Context Window Management.", type: "System Design", phase: 3 },
  { title: "Designing for DevOps", aha: "CI/CD Pipelines, Blue-Green Deployment, Canary Releases.", type: "System Design", phase: 3 },
  { title: "Distributed Locking", aha: "Redis Redlock, ZooKeeper ephemeral nodes.", type: "System Design", phase: 3 },
  { title: "Leader Election", aha: "Raft, Paxos, Bully Algorithm.", type: "System Design", phase: 3 },
  { title: "Design YouTube/Netflix", aha: "CDN optimization, Adaptive Bitrate Streaming, Pre-fetching.", type: "System Design", phase: 3 },
  { title: "Design Google Drive/Dropbox", aha: "Chunking, Differential Sync, Block storage.", type: "System Design", phase: 3 },
  { title: "Distributed Counters", aha: "Sharded counters for high write throughput.", type: "System Design", phase: 3 },
  { title: "Design Typeahead Suggestions", aha: "Trie structure, Top-k caching.", type: "System Design", phase: 3 },
  { title: "Design Near-By Friends (Location)", aha: "Quadtrees, Geohashing.", type: "System Design", phase: 3 },
];
